/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Condition = { 'buenEstado' : null } |
  { 'nueva' : null } |
  { 'usada' : null } |
  { 'comoNueva' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface GarmentFilter {
  'size' : [] | [string],
  'search' : [] | [string],
  'garmentType' : [] | [string],
  'modality' : [] | [Modality],
  'condition' : [] | [Condition],
}
export type GarmentId = bigint;
export interface GarmentView {
  'id' : GarmentId,
  'createdAt' : Timestamp,
  'size' : string,
  'description' : string,
  'photoUrl' : string,
  'garmentType' : string,
  'modality' : Modality,
  'condition' : Condition,
}
export interface ImpactMetrics {
  'garmentsReused' : bigint,
  'peopleBenefited' : bigint,
  'donationsMade' : bigint,
}
export type Modality = { 'venta' : bigint } |
  { 'donacion' : null } |
  { 'intercambio' : null };
export interface NewGarment {
  'size' : string,
  'description' : string,
  'photoUrl' : string,
  'garmentType' : string,
  'modality' : Modality,
  'condition' : Condition,
}
export interface NewStory {
  'title' : string,
  'deliveredAt' : Timestamp,
  'garmentsDelivered' : bigint,
  'description' : string,
  'photoUrl' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type StoryId = bigint;
export interface StoryView {
  'id' : StoryId,
  'title' : string,
  'deliveredAt' : Timestamp,
  'garmentsDelivered' : bigint,
  'description' : string,
  'photoUrl' : string,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'addGarment' : ActorMethod<[NewGarment], GarmentView>,
  'addStory' : ActorMethod<[NewStory], StoryView>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGarment' : ActorMethod<[GarmentId], [] | [GarmentView]>,
  'getImpactMetrics' : ActorMethod<[], ImpactMetrics>,
  'getStory' : ActorMethod<[StoryId], [] | [StoryView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listGarments' : ActorMethod<[GarmentFilter], Array<GarmentView>>,
  'listStories' : ActorMethod<[], Array<StoryView>>,
  'schema' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];