/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Modality = IDL.Variant({
  'venta' : IDL.Nat,
  'donacion' : IDL.Null,
  'intercambio' : IDL.Null,
});
export const Condition = IDL.Variant({
  'buenEstado' : IDL.Null,
  'nueva' : IDL.Null,
  'usada' : IDL.Null,
  'comoNueva' : IDL.Null,
});
export const NewGarment = IDL.Record({
  'size' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'garmentType' : IDL.Text,
  'modality' : Modality,
  'condition' : Condition,
});
export const GarmentId = IDL.Nat;
export const Timestamp = IDL.Int;
export const GarmentView = IDL.Record({
  'id' : GarmentId,
  'createdAt' : Timestamp,
  'size' : IDL.Text,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'garmentType' : IDL.Text,
  'modality' : Modality,
  'condition' : Condition,
});
export const NewStory = IDL.Record({
  'title' : IDL.Text,
  'deliveredAt' : Timestamp,
  'garmentsDelivered' : IDL.Nat,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const StoryId = IDL.Nat;
export const StoryView = IDL.Record({
  'id' : StoryId,
  'title' : IDL.Text,
  'deliveredAt' : Timestamp,
  'garmentsDelivered' : IDL.Nat,
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const ImpactMetrics = IDL.Record({
  'garmentsReused' : IDL.Nat,
  'peopleBenefited' : IDL.Nat,
  'donationsMade' : IDL.Nat,
});
export const GarmentFilter = IDL.Record({
  'size' : IDL.Opt(IDL.Text),
  'search' : IDL.Opt(IDL.Text),
  'garmentType' : IDL.Opt(IDL.Text),
  'modality' : IDL.Opt(Modality),
  'condition' : IDL.Opt(Condition),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addGarment' : IDL.Func([NewGarment], [GarmentView], []),
  'addStory' : IDL.Func([NewStory], [StoryView], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGarment' : IDL.Func([GarmentId], [IDL.Opt(GarmentView)], ['query']),
  'getImpactMetrics' : IDL.Func([], [ImpactMetrics], ['query']),
  'getStory' : IDL.Func([StoryId], [IDL.Opt(StoryView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listGarments' : IDL.Func([GarmentFilter], [IDL.Vec(GarmentView)], ['query']),
  'listStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Modality = IDL.Variant({
    'venta' : IDL.Nat,
    'donacion' : IDL.Null,
    'intercambio' : IDL.Null,
  });
  const Condition = IDL.Variant({
    'buenEstado' : IDL.Null,
    'nueva' : IDL.Null,
    'usada' : IDL.Null,
    'comoNueva' : IDL.Null,
  });
  const NewGarment = IDL.Record({
    'size' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'garmentType' : IDL.Text,
    'modality' : Modality,
    'condition' : Condition,
  });
  const GarmentId = IDL.Nat;
  const Timestamp = IDL.Int;
  const GarmentView = IDL.Record({
    'id' : GarmentId,
    'createdAt' : Timestamp,
    'size' : IDL.Text,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'garmentType' : IDL.Text,
    'modality' : Modality,
    'condition' : Condition,
  });
  const NewStory = IDL.Record({
    'title' : IDL.Text,
    'deliveredAt' : Timestamp,
    'garmentsDelivered' : IDL.Nat,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const StoryId = IDL.Nat;
  const StoryView = IDL.Record({
    'id' : StoryId,
    'title' : IDL.Text,
    'deliveredAt' : Timestamp,
    'garmentsDelivered' : IDL.Nat,
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const ImpactMetrics = IDL.Record({
    'garmentsReused' : IDL.Nat,
    'peopleBenefited' : IDL.Nat,
    'donationsMade' : IDL.Nat,
  });
  const GarmentFilter = IDL.Record({
    'size' : IDL.Opt(IDL.Text),
    'search' : IDL.Opt(IDL.Text),
    'garmentType' : IDL.Opt(IDL.Text),
    'modality' : IDL.Opt(Modality),
    'condition' : IDL.Opt(Condition),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addGarment' : IDL.Func([NewGarment], [GarmentView], []),
    'addStory' : IDL.Func([NewStory], [StoryView], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGarment' : IDL.Func([GarmentId], [IDL.Opt(GarmentView)], ['query']),
    'getImpactMetrics' : IDL.Func([], [ImpactMetrics], ['query']),
    'getStory' : IDL.Func([StoryId], [IDL.Opt(StoryView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listGarments' : IDL.Func(
        [GarmentFilter],
        [IDL.Vec(GarmentView)],
        ['query'],
      ),
    'listStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };